job: extension
config:
  name: nowy_dataset_1.3
  process:
  - type: sd_trainer
    training_folder: output
    device: cuda:0
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 2000
      max_step_saves_to_keep: 1
      push_to_hub: false
    datasets:
    - folder_path: /workspace/training_data/matt_training_test
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
      - 1024
      - 1280
    train:
      batch_size: 1
      steps: 2000
      gradient_accumulation_steps: 4
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0001
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: true
    sample:
      sampler: flowmatch
      sample_every: 100
      width: 1024
      height: 1280
      prompts:
      - Matt, photo
      - Matt, portrait, upper body  
      - Matt, shirtless, full body, photo
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 20